signup:
  weekday: friday
  start: '10:00'
  end: '12:00'
lesson:
  weekday: thursday
  time: '14:30'
  capacity: 6
  cancel_deadline_hours: 4
email:
- fri.uni-lj.si
- fe.uni-lj.si
algorithm:
  name: LPV
  weight_exponent: 1.0
